---
- hosts: cloud
  # become: yes
  # become_user: vagrant
  sudo: yes
  gather_facts: yes
  vars_files:
    - vars/main.yaml
  roles:
    - geerlingguy.nodejs



  vars:
    # Vars can also be passed in via CLI with `--extra-vars="name=value"`.
    #node_apps_location: /usr/local/opt/node
    


  tasks:
    # - name: Install Node.js
    #   apt: name={{item}} state=latest update_cache=yes upgrade=yes
    #   with_items:
    #     - nodejs
    #     - npm
    # - name: Update alternatives.
    #   command: update-alternatives --install /usr/bin/node node /usr/bin/nodejs 10

    - name: Install Forever (to run our Node.js app).
      npm: 
        name: forever
        global: yes
        state: latest
    - name: Install Nodemon 
      npm:
        name: nodemon
        global: yes
        state: latest
    # - name: Ensure Node.js app folder exists.
    #   file: "path={{ node_apps_location }} state=directory"

    # - name: get remote username
    #   command: whoami
    #   register: username_on_remote

    # - name: Copy example Node.js app to server.
    #   copy: "src=../../cloud dest={{ node_apps_location }}"

    # - name: Install app dependencies defined in package.json.
    #   npm: "path={{ node_apps_location }}/app"

    - name: Check list of running Node.js apps.
      command: forever list
      register: forever_list
      changed_when: false

    - name: Start example Node.js app.
      command: "forever start {{ node_apps_location }}/built/app.js"
      when: "forever_list.stdout.find('{{ node_apps_location }}/built/app.js') == -1"